name: UnitedChat
version: '${project.version}'
main: org.unitedlands.unitedchat.UnitedChat
api-version: 1.21
authors: [ Maroon28 ]
contributors: [ Litning11, Theriel_, G0STG0D ]
depend: [ Towny, TownyChat ]
softdepend: [ UnitedLib, PlaceholderAPI, Vault ]
commands:
  unitedchat:
    description: Toggles chat features
    aliases:
      - unitedchat
      - uc
